import random

ALPHAS_DISPONIBLES = [
    "mewtwo",
    "rayquaza",
    "groudon",
    "kyogre",
    "dialga",
    "palkia",
    "giratina-altered",
    "reshiram",
    "zekrom",
    "kyurem",
    "xerneas",
    "yveltal",
    "zacian-hero",
    "zamazenta-hero",
    "koraidon",
    "miraidon",

    "dragonite",
    "tyranitar",
    "metagross",
    "salamence",
    "garchomp",
    "hydreigon",
    "goodra",
    "kommo-o",
    "dragapult",
    "baxcalibur",

    "charizard",
    "venusaur",
    "blastoise",
    "sceptile",
    "blaziken",
    "swampert",
    "infernape",
    "empoleon",
    "serperior",
    "emboar",
    "samurott",
    "greninja",
    "decidueye",
    "incineroar",
    "primarina",
    "rillaboom",
    "cinderace",
    "inteleon",
    "meowscarada",
    "skeledirge",
    "quaquaval",

    "lucario",
    "volcarona",
    "mamoswine",
    "togekiss",
    "aegislash",
    "excadrill",
    "conkeldurr",
    "kingambit",
    "ursaluna",
    "annihilape",
    "ceruledge",
    "armarouge",
    "gholdengo",
    "dragalge",
    "iron-valiant"
]

def obtener_alpha_aleatorio():
    return random.choice(ALPHAS_DISPONIBLES)